services:
  local-api:
    build: .
    container_name: gloomy-newton
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - 8080:80
    volumes:
      - .:/app